"""Generate the offline data modules used by the WeChat Mini Program.

The website's ``data/site_dataset.json`` remains the only question-data source.
This script groups records by exam year so that the Mini Program can load a
small JavaScript module at a time and does not require a network request.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "site_dataset.json"
OUTPUT = ROOT / "miniprogram" / "data" / "questions"


def js_module(value: object) -> str:
    return "module.exports = " + json.dumps(value, ensure_ascii=False, separators=(",", ":")) + ";\n"


def main():
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    by_year: dict[int, list[dict]] = defaultdict(list)
    for question in payload["questions"]:
        by_year[question["year"]].append(question)

    OUTPUT.mkdir(parents=True, exist_ok=True)
    years = sorted(by_year, reverse=True)
    for year in years:
        (OUTPUT / f"{year}.js").write_text(js_module(by_year[year]), encoding="utf-8")

    loaders = ["// Generated by scripts/build_miniprogram_data.py. Do not edit by hand."]
    for year in years:
        loaders.append(f"const y{year} = require('./questions/{year}.js');")
    loaders.append("const byYear = {" + ",".join(f"{year}:y{year}" for year in years) + "};")
    loaders.append("const years = [" + ",".join(map(str, years)) + "];")
    loaders.append("function loadAllQuestions(){return years.flatMap(year=>byYear[year]);}")
    loaders.append("module.exports={years,byYear,loadAllQuestions};")
    (ROOT / "miniprogram" / "data" / "loaders.js").write_text("\n".join(loaders) + "\n", encoding="utf-8")

    meta = {
        "edition": payload["meta"]["edition"],
        "questions": len(payload["questions"]),
        "years": years,
        "generated": payload["meta"]["generated"],
    }
    (ROOT / "miniprogram" / "data" / "meta.js").write_text(js_module(meta), encoding="utf-8")
    print(f"Built Mini Program data: {len(payload['questions'])} questions across {len(years)} years")


if __name__ == "__main__":
    main()
